# Generated by Django 2.0.3 on 2018-04-09 18:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alignment',
            name='timestamps',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), size=2), blank=True, null=True, size=None),
        ),
    ]
