# Generated by Django 2.0.3 on 2018-04-02 17:07

from django.db import migrations, models
import services.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lyrics', models.FileField(upload_to=services.utils.update_filename)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Designates when the composition is created.', verbose_name='created at')),
            ],
            options={
                'verbose_name': 'composition',
                'verbose_name_plural': 'compositions',
                'db_table': 'composition',
            },
        ),
    ]
